### ISSUE TITLE
I'm Trying to run it in notepad but it isnt working is it only for rasberry pi?

### ISSUE THREAD

**Issue by ghost** [stuartsoft/twitchqueue#1]
Error: Livestreamer is not an external Bathfile.

Command in Notepad++ Run: C:\Python34\Lib\idlelib\idle.py C:\Users\Hamza\Desktop\PiStream\Twitch\Bookmarks\Twitch.py

Please Reply :D

**Comment by stuartsoft** [comment]
Sounds like Livestreamer may not be installed on your system. You can get an installer for it from the livestreamer website: http://docs.livestreamer.io/install.html#windows-binaries

Additionally, try running the script from command prompt:

```
python twitchqueue.py
```

The script was developed for use on the RPI, but I've been using on my Windows laptop as well

**Comment by ghost** [comment]
Thank you!
